# Generated by Django 5.2.1 on 2025-06-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_kg', models.FloatField()),
                ('category', models.CharField(choices=[('PET', 'PET'), ('HDPE', 'HDPE'), ('LDPE', 'LDPE'), ('PP', 'PP'), ('Other', 'Other')], max_length=20)),
                ('region', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
