# Generated by Django 5.2.1 on 2025-06-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('3D-PRINTS', '3D-PRINTS'), ('BALES', 'BALES'), ('PELLETS', 'PELLETS'), ('JEWELLERY', 'JEWELLERY'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(upload_to='assets/img/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
