# Generated by Django 5.2.1 on 2025-06-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
