# Generated by Django 5.2.1 on 2025-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('3D-PRINTS', '3D-PRINTS'), ('BALES', 'BALES'), ('PELLETS', 'PELLETS'), ('JEWELLERY', 'JEWELLERY'), ('FLAKES', 'FLAKES'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
