# Generated by Django 5.2.1 on 2025-06-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_employee_job_profile_project_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(upload_to='assets/img/'),
        ),
    ]
