# Generated by Django 5.2.4 on 2025-09-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_partner_alter_plasticcollection_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
